name = "xes-software/token-swapping"
version = "0.0.0"
compiler = "v1.1.12"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'xes-software/token-swapping'"

[repository]
user = "xes-software"
project = "token-swapping"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
